# Generated by Django 4.0.6 on 2022-07-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='student',
            name='customerId',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='discount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='productId',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='qty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='subTotal',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
