# Generated by Django 4.0.6 on 2022-07-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qty',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
